version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "comparefaces"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vacuu0axkfh7"
s3_prefix = "comparefaces"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
